### ISSUE TITLE
undefined method `new' for "Rack::Bug":String>

### ISSUE THREAD

**Issue by jarl-dk** [brynary/rack-bug#19]
I have installed the gem

I have added the line
        config.middleware.use "Rack::Bug", :secret_key => "adsfl232343sdfs24759uweafsdfsd5234"
to my `environments/development.rb`

I can start the server, but when I hit my application by pointing my browser to
    http://localhost:3000/**rack_bug**/bookmarklet.html
I get the error:
    hermes157~/projects/inseeto/pegasus-performance:./script/server
    => Booting Mongrel
    => Rails 2.3.5 application starting on http://0.0.0.0:3000
    => Call with -d to detach
    => Ctrl-C to shutdown server
    Thu Jul 08 13:44:49 +0200 2010: Read error: #<NoMethodError: undefined method `new' for "Rack::Bug":String>
    /var/lib/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/middleware_stack.rb:72:in `build'
    /var/lib/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/middleware_stack.rb:116:in`build'
    /var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:440:in `inject'
    /var/lib/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/middleware_stack.rb:116:in`each'
    /var/lib/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/middleware_stack.rb:116:in `inject'
    /var/lib/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/middleware_stack.rb:116:in`build'
    /var/lib/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:130:in `build_middleware_stack'
    /var/lib/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:113:in`call'
    /var/lib/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/reloader.rb:34:in `run'
    /var/lib/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:108:in`call'
    /var/lib/gems/1.8/gems/rails-2.3.5/lib/rails/rack/static.rb:31:in `call'
    /var/lib/gems/1.8/gems/rack-1.0.1/lib/rack/urlmap.rb:46:in`call'
    /var/lib/gems/1.8/gems/rack-1.0.1/lib/rack/urlmap.rb:40:in `each'
    /var/lib/gems/1.8/gems/rack-1.0.1/lib/rack/urlmap.rb:40:in`call'
    /var/lib/gems/1.8/gems/rails-2.3.5/lib/rails/rack/log_tailer.rb:17:in `call'
    /var/lib/gems/1.8/gems/rack-1.0.1/lib/rack/content_length.rb:13:in`call'
    /var/lib/gems/1.8/gems/rack-1.0.1/lib/rack/chunked.rb:15:in `call'
    /var/lib/gems/1.8/gems/rack-1.0.1/lib/rack/handler/mongrel.rb:64:in`process'
    /var/lib/gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:159:in `process_client'
    /var/lib/gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:158:in`each'
    /var/lib/gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:158:in `process_client'
    /var/lib/gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:285:in`run'
    /var/lib/gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:285:in `initialize'
    /var/lib/gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:285:in`new'
    /var/lib/gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:285:in `run'
    /var/lib/gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:268:in`initialize'
    /var/lib/gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:268:in `new'
    /var/lib/gems/1.8/gems/mongrel-1.1.5/lib/mongrel.rb:268:in`run'
    /var/lib/gems/1.8/gems/rack-1.0.1/lib/rack/handler/mongrel.rb:34:in `run'
    /var/lib/gems/1.8/gems/rails-2.3.5/lib/commands/server.rb:111
    /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
    /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
    ./script/server:3

Jarl

**Comment by josevalim** [comment]
Have you tried giving Rack::Bug as constant instead of string?

**Comment by jarl-dk** [comment]
No. I just followed the guide: http://github.com/brynary/rack-bug. I'll try it soon.

**Comment by jarl-dk** [comment]
Now I have tried
    config.middleware.use Rack::Bug, :secret_key => "adsfl232343sdfs24759uweafsdfsd5234"
as well, but now it won't even start my server. it says
    => Booting Mongrel
    => Rails 2.3.5 application starting on http://0.0.0.0:3000
    /var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:440:in `load_missing_constant': uninitialized constant Rails::Rack::Bug (NameError)
            from /var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:80:in`const_missing'
            from /home/jarl/projects/inseeto/pegasus-test_refactor/config/environments/development.rb:58:in `load_environment'
            from /var/lib/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:386:in`load_environment'
            from /var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/kernel/reporting.rb:11:in `silence_warnings'
            from /var/lib/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:379:in`load_environment'
            from /var/lib/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:137:in `process'
            from /var/lib/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:113:in`send'
            from /var/lib/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:113:in `run'
            from /home/jarl/projects/inseeto/pegasus-test_refactor/config/environment.rb:14
            from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
            from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
            from /var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in`require'
            from /var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in `new_constants_in'
            from /var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in`require'
            from /var/lib/gems/1.8/gems/rails-2.3.5/lib/commands/server.rb:84
            from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
            from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
            from ./script/server:3

**Comment by josevalim** [comment]
Oh, try ::Rack::Bug instead of Rack::Bug.

**Comment by jarl-dk** [comment]
Done. Same problem, server wont start with ST as above.

**Comment by mattetti** [comment]
```
require 'rack/bug'
config.middleware.use ::Rack::Bug, :secret_key => "adsfl232343sdfs24759uweafsdfsd5234"
```

**Comment by paulbjensen** [comment]
Guys, I'm not having any luck getting this running (Rails 3.0.9 on Ruby 1.9.2):

```
ruby-1.9.2-p290/gems/activesupport-3.0.9/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method': undefined method `render_template' for class `ActionView::Template' (NameError)
ruby-1.9.2-p290/gems/activesupport-3.0.9/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method_chain'
ruby-1.9.2-p290/gems/rack-bug-0.3.0/lib/rack/bug/panels/templates_panel/actionview_extension.rb:10:in `block in <top (required)>'
ruby-1.9.2-p290/gems/rack-bug-0.3.0/lib/rack/bug/panels/templates_panel/actionview_extension.rb:2:in `class_eval'
ruby-1.9.2-p290/gems/rack-bug-0.3.0/lib/rack/bug/panels/templates_panel/actionview_extension.rb:2:in `<top (required)>'
ruby-1.9.2-p290/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in `require'
ruby-1.9.2-p290/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in `block in require'
ruby-1.9.2-p290/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:225:in `block in load_dependency'
ruby-1.9.2-p290/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:596:in `new_constants_in'
ruby-1.9.2-p290/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:225:in `load_dependency'
ruby-1.9.2-p290/gems/activesupport-3.0.9/lib/active_support/dependencies.rb:239:in `require'
ruby-1.9.2-p290/gems/rack-bug-0.3.0/lib/rack/bug/panels/templates_panel.rb:5:in `<class:TemplatesPanel>'
ruby-1.9.2-p290/gems/rack-bug-0.3.0/lib/rack/bug/panels/templates_panel.rb:4:in `<module:Bug>'
ruby-1.9.2-p290/gems/rack-bug-0.3.0/lib/rack/bug/panels/templates_panel.rb:2:in `<module:Rack>'
ruby-1.9.2-p290/gems/rack-bug-0.3.0/lib/rack/bug/panels/templates_panel.rb:1:in `<top (required)>'
ruby-1.9.2-p290/gems/rack-bug-0.3.0/lib/rack/bug/options.rb:80:in `initialize_options'
ruby-1.9.2-p290/gems/rack-bug-0.3.0/lib/rack/bug/toolbar.rb:29:in `initialize'
ruby-1.9.2-p290/gems/rack-bug-0.3.0/lib/rack/bug.rb:43:in `new'
ruby-1.9.2-p290/gems/rack-bug-0.3.0/lib/rack/bug.rb:43:in `new'
```
