### ISSUE TITLE
"type mismatch: Pathname given" error on root page

### ISSUE THREAD

**Issue by rnhurt** [brynary/rack-bug#20]
Site details:
- Ruby 1.9.1
- Rails 2.3.5
- Ubuntu 10.4

I am getting the following error when I visit the root page of my site in development mode:

```
Completed in 386ms (View: 370, DB: 8) | 200 OK [http://localhost/]
/!\ FAILSAFE /!\  2010-07-16 08:52:28 -0400
 Status: 500 Internal Server Error
type mismatch: Pathname given
/var/www/gradesheet/vendor/plugins/rack-bug/lib/rack/bug/filtered_backtrace.rb:16:in `index'
/var/www/gradesheet/vendor/plugins/rack-bug/lib/rack/bug/filtered_backtrace.rb:16:in `block in filtered_backtrace'
/var/www/gradesheet/vendor/plugins/rack-bug/lib/rack/bug/filtered_backtrace.rb:14:in `select'
/var/www/gradesheet/vendor/plugins/rack-bug/lib/rack/bug/filtered_backtrace.rb:14:in `filtered_backtrace'
/var/www/gradesheet/vendor/plugins/rack-bug/lib/rack/bug/filtered_backtrace.rb:10:in `has_backtrace?'
panels/sql:20:in `block in panels_sql_locals_queries'
panels/sql:15:in `each'
panels/sql:15:in `panels_sql_locals_queries'
/var/www/gradesheet/vendor/plugins/rack-bug/lib/rack/bug/render.rb:20:in `render_template'
/var/www/gradesheet/vendor/plugins/rack-bug/lib/rack/bug/panels/sql_panel.rb:47:in `content'
toolbar:38:in `block in toolbar_locals_panels'
toolbar:34:in `each'
toolbar:34:in `toolbar_locals_panels'
/var/www/gradesheet/vendor/plugins/rack-bug/lib/rack/bug/render.rb:20:in `render_template'
/var/www/gradesheet/vendor/plugins/rack-bug/lib/rack/bug/toolbar.rb:58:in `render'
/var/www/gradesheet/vendor/plugins/rack-bug/lib/rack/bug/toolbar.rb:46:in `inject_toolbar'
/var/www/gradesheet/vendor/plugins/rack-bug/lib/rack/bug/toolbar.rb:22:in `call'
/var/www/gradesheet/vendor/plugins/rack-bug/lib/rack/bug.rb:42:in `call'
/var/lib/gems/1.9.1/gems/actionpack-2.3.5/lib/action_controller/string_coercion.rb:25:in `call'
/var/lib/gems/1.9.1/gems/rack-1.0.1/lib/rack/head.rb:9:in `call'
/var/lib/gems/1.9.1/gems/rack-1.0.1/lib/rack/methodoverride.rb:24:in `call'
/var/lib/gems/1.9.1/gems/actionpack-2.3.5/lib/action_controller/params_parser.rb:15:in `call'
/var/lib/gems/1.9.1/gems/actionpack-2.3.5/lib/action_controller/session/cookie_store.rb:93:in `call'
/var/lib/gems/1.9.1/gems/actionpack-2.3.5/lib/action_controller/failsafe.rb:26:in `call'
/var/lib/gems/1.9.1/gems/rack-1.0.1/lib/rack/lock.rb:11:in `block in call'
<internal:prelude>:8:in `synchronize'
/var/lib/gems/1.9.1/gems/rack-1.0.1/lib/rack/lock.rb:11:in `call'
/var/lib/gems/1.9.1/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:114:in `block in call'
/var/lib/gems/1.9.1/gems/actionpack-2.3.5/lib/action_controller/reloader.rb:34:in `run'
/var/lib/gems/1.9.1/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:108:in `call'
/var/lib/gems/1.9.1/gems/rails-2.3.5/lib/rails/rack/static.rb:31:in `call'
/var/lib/gems/1.9.1/gems/rack-1.0.1/lib/rack/urlmap.rb:46:in `block in call'
/var/lib/gems/1.9.1/gems/rack-1.0.1/lib/rack/urlmap.rb:40:in `each'
/var/lib/gems/1.9.1/gems/rack-1.0.1/lib/rack/urlmap.rb:40:in `call'
/var/lib/gems/1.9.1/gems/rails-2.3.5/lib/rails/rack/debugger.rb:19:in `call'
/var/lib/gems/1.9.1/gems/rails-2.3.5/lib/rails/rack/log_tailer.rb:17:in `call'
/var/lib/gems/1.9.1/gems/rack-1.0.1/lib/rack/content_length.rb:13:in `call'
/var/lib/gems/1.9.1/gems/rack-1.0.1/lib/rack/chunked.rb:15:in `call'
/var/lib/gems/1.9.1/gems/rack-1.0.1/lib/rack/handler/mongrel.rb:64:in `process'
/var/lib/gems/1.9.1/gems/mongrel-1.2.0.pre2/lib/mongrel.rb:165:in `block in process_client'
/var/lib/gems/1.9.1/gems/mongrel-1.2.0.pre2/lib/mongrel.rb:164:in `each'
/var/lib/gems/1.9.1/gems/mongrel-1.2.0.pre2/lib/mongrel.rb:164:in `process_client'
/var/lib/gems/1.9.1/gems/mongrel-1.2.0.pre2/lib/mongrel.rb:291:in `block (2 levels) in run'
Rendering template within layouts/application
```

My default route is
    # By default, we want the user to see the "dashboard" page.
    map.root :controller => "dashboard"

It looks like the <code>filtered_backtrace.rb</code> code is expecting a list of something but it is getting a list of pathnames.

**Comment by amithgeorge** [comment]
Same issue. Rails 2.3.8 on Ruby 1.9.1-p378 on Ubuntu 10.4. Am running passenger on nginx with mysql db.
